version: "3.9"

services:
  transcriber:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - AI_DETECTOR_KEY=${AI_DETECTOR_KEY}
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
